### ISSUE TITLE
[workflow] pnpm setupを使う

### ISSUE THREAD

**Issue by naruse666** [TECH-C-LT/Peace-Net#70]
pnpm公式のインストーラーを利用する。
https://github.com/pnpm/action-setup
```yaml
- name: Setup Node.js
  uses: actions/setup-node@v4
  with:
    node-version: '18'  # Node.jsのバージョンを指定

- name: Install pnpm
  uses: pnpm/action-setup@v2
  with:
    version: 8  # pnpmのバージョンを指定

- name: Install dependencies
  run: pnpm install
  working-directory: apps/api  # 作業ディレクトリを指定
```
